version: '3.5'

services:
##### pgsql s.
  postgresql:
    image: postgres
    container_name: postgresContainer
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: testadmin
      POSTGRES_PASSWORD: testpwd
      POSTGRES_DB: testdb
    # volumes:
    #    - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testadmin -d testdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

    deploy:
        resources:
            limits:
                cpus: '1'
                memory: 4G

##### pgAdmin s.
  pgadmin:
    container_name: pgadminContainer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    # volumes:
    #    - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

  # testApi:
  #   container_name: testServer
  #   build: ./
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: